from playwright.sync_api import Playwright, sync_playwright, expect
import time

def run(playwright: Playwright) -> None:
    start = time.time()
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://localhost:7077/")
    page.get_by_placeholder("Email").click()
    page.get_by_placeholder("Email").fill("Yoel@wi-bash.fr")
    page.get_by_placeholder("Email").press("Tab")
    page.get_by_placeholder("Mot de Passe").fill("Yoel971#")
    page.get_by_placeholder("Mot de Passe").press("Enter")
    page.get_by_placeholder("Recherche").click()
    page.get_by_role("button").click()
    page.get_by_role("link", name="Tenants Azure AD").click()
    page.get_by_role("link", name="Nouveau").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("row", name="Karukero Modifier Détails Supprimer").get_by_role("link", name="Modifier").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("row", name="Karukero Modifier Détails Supprimer").get_by_role("link", name="Détails").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("row", name="Karukero Modifier Détails Supprimer").get_by_role("link", name="Supprimer").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Sociétés").click()
    page.get_by_role("link", name="Nouveau").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("row", name="Karukero a1e924c7-f470-43f9-8c27-a7826f67876c Modifier Détails Supprimer").get_by_role("link", name="Modifier").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("row", name="Karukero a1e924c7-f470-43f9-8c27-a7826f67876c Modifier Détails Supprimer").get_by_role("link", name="Détails").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("row", name="Karukero a1e924c7-f470-43f9-8c27-a7826f67876c Modifier Détails Supprimer").get_by_role("link", name="Supprimer").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Profils").click()
    page.get_by_role("link", name="Nouveau").click()
    page.get_by_role("link", name="Retour à la liste").click()
    page.get_by_role("row", name="Exploitation Editer Utilisateurs Editer Services Delete").get_by_role("link", name="Editer Utilisateurs").click()
    page.get_by_role("button", name="Quitter").click()
    page.get_by_role("row", name="Exploitation Editer Utilisateurs Editer Services Delete").get_by_role("link", name="Editer Services").click()
    page.get_by_role("button", name="Quitter").click()
    page.get_by_role("row", name="Exploitation Editer Utilisateurs Editer Services Delete").get_by_role("link", name="Delete").click() # Problème Supression de Profile
    page.goto("https://localhost:7077/Role/Index")
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Utilisateurs", exact=True).click()
    page.get_by_role("link", name="Nouveau").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Rapports").click()
    page.get_by_role("link", name="Nouveau").click()
    page.get_by_role("link", name="Retour à la liste").click()
    page.get_by_role("row", name="Commission_filter 03530192-f97f-4b2a-9f67-54721604fb00 757dfada-5ec5-4e54-b015-415fc4eb72b2 Commercial Digitom Modifier Détails Supprimer").get_by_role("link", name="Modifier").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("row", name="Commission_filter 03530192-f97f-4b2a-9f67-54721604fb00 757dfada-5ec5-4e54-b015-415fc4eb72b2 Commercial Digitom Modifier Détails Supprimer").get_by_role("link", name="Détails").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("row", name="Commission_filter 03530192-f97f-4b2a-9f67-54721604fb00 757dfada-5ec5-4e54-b015-415fc4eb72b2 Commercial Digitom Modifier Détails Supprimer").get_by_role("link", name="Supprimer").click()
    page.get_by_role("link", name="Revenir à la liste").click()
    page.get_by_role("button", name="Déconnexion").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()
    end = time.time()
    print(end - start)


with sync_playwright() as playwright:
    run(playwright)
